name: 'build-with-nixpack'

on:
   push:
      branches: [main]

jobs:
   build-with-nixpack:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: curl -sSL https://nixpacks.com/install.sh | bash
         - run: nixpacks build ./apps/server --name my-app
